# Generated by Django 2.2 on 2023-12-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='is_verified',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='otp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
