# Generated by Django 2.2 on 2023-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20231207_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=500)),
                ('short_url', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
