# Generated by Django 2.2 on 2023-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='username',
        ),
        migrations.AddField(
            model_name='operation',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
